"""establish relationship and add foreign key

Revision ID: c6d16e02861f
Revises: 4cc9bbe658ad
Create Date: 2025-06-02 10:55:00.220263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d16e02861f'
down_revision: Union[str, None] = '4cc9bbe658ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_contracts_vendor_id_vendors'), 'vendors', ['vendor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_contracts_project_id_projects'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('performance_reviews', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_performance_reviews_contract_id_contracts'), 'contracts', ['contract_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_performance_reviews_contract_id_contracts'), type_='foreignkey')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contracts_project_id_projects'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contracts_vendor_id_vendors'), type_='foreignkey')

    # ### end Alembic commands ###
